### ISSUE TITLE
Use intra domain tests to ensure that main doesn't break

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#142]
**Tech Notes**
It is assumed that the solution is based on Renés idea and PR about spinning up an intermediate environment when creating a PR and deprovisioned when closing/merging the PR.

Please beware that the story is time-boxed.

**Acceptance Criteria**
AC1: Intra domain tests are executed in pipelines as part of PR gateway

**Comment by BjarkeMeier** [comment]
Original text (moved to here to keep description short and focused):

Broken pipelines should have a high priority to get fixed ASAP. Apparently, that doesn't always happen. As described here, we recently had an incident where the deployment of infrastructure was broken for 4-6 days without anyone in the team reacting (or even noticing?). The problem was also made public to everybody on the landing page of the geh-charges repo.

Should we take any action to prevent such situations in the future? Personally, I (BJM) believe so as we should strive to always be able to immediately deploy new features or more importantly critical fixes. Until going into production is an excellent opportunity to learn and improve.

**Comment by bemwen** [comment]
**Test result:**

AC1: Intra domain tests are executed in pipelines as part of PR gateway - PASSED

**AC1:** 

Was run as part of PR 408.

As it can be seen in the below screenshot, the integration tests were executed succesfully.

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/f9043a6a-7a6c-4469-8769-2abfde1bf8b7)

Logs from the run can be found here https://github.com/Energinet-DataHub/geh-charges/pull/408/checks?check_run_id=3018244758
