### ISSUE TITLE
Update snapshot on "ChargeCommandAccepted"

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#170]
Save the charges on event "ChargeMessageBusinessValidationSucceeded".
Use our existing SQL model.
The term "snapshot" in the title stems from the event sourcing pattern that we seem to be using.
Do we want to publish an event as it is probably not needed?

Dependencies:
The DH3 SQL Server
Guidelines on how to use the SQL Server (regarding own schema, protection/isolation etc)
Antagelser:
Databasen er flyttet på dette tidspunkt
Kun enabler-delen skal laves. Resten bliver løst under spill-over stories for BRS 31-33

Notes for tester
We only support create commands at the moment since reading from db fails thus causing update and stop to fail. I, however, consider that acceptable at the moment as we don't have the business logic in place to handle update and stop correctly at the moment. Let me know if you don't agree.
Also, I didn't test this my self but Michael did yesterday as part of getting the "big code design" PR done.

ACs
AC1: Charge data is stored in the database when event "ChargeCommandAccepted" is received.

**Comment by bemwen** [comment]
Tested with the following lenience: Persisting doesnt actually happen as a result of the Accepted event anymore, but as part of its flow.

With that in mind, I have tested by seeing that a create charge that has been received and validated is succesfully stored in the database when an accept event is also published as a result.

**Result:**
AC1: Charge data is stored in the database when event "ChargeCommandAccepted" is received - SUCCESS

Note: A bug was found in the saved data caused by work previous to this story. It has been decided to move this story towards closed and work with the bug separately instead. The bug can be found here:

https://github.com/Energinet-DataHub/geh-charges/issues/185

**AC1:**
Has been tested in the T-environment.

_Subscription:_
A valid charge is sent using our "Submit Addition Subscription" message with charge ID of "XMDJESUB02".

![image](https://user-images.githubusercontent.com/12642168/116883954-76fda080-ac26-11eb-919d-943e59acfdb7.png)

The message result in an accepted event:

![image](https://user-images.githubusercontent.com/12642168/116884174-bb893c00-ac26-11eb-96a7-b6942d50bb51.png)

The subscription ended up in the Charges table as desired:

![image](https://user-images.githubusercontent.com/12642168/116884365-f4c1ac00-ac26-11eb-85d9-c8fa684a2d05.png)

_Fee:_
A valid charge is sent using our "Submit Addition Fee" message with charge ID of "XMDJEFEE01".

![image](https://user-images.githubusercontent.com/12642168/116988573-db753a00-acd0-11eb-9936-ec03d4b423ba.png)

The message result in an accepted event:

![image](https://user-images.githubusercontent.com/12642168/116988720-0c556f00-acd1-11eb-97bc-7e598ba47b86.png)

The fee ended up in the Charges table as desired:

![image](https://user-images.githubusercontent.com/12642168/116988770-1f683f00-acd1-11eb-835d-b9ca2f8512a4.png)

_Tariff, fixed price:_
A valid charge is sent using our "Submit Addition Tariff, fixed price" message with ID of "XMDJETAF01".

![image](https://user-images.githubusercontent.com/12642168/116989033-8259d600-acd1-11eb-840d-09b77bbf64d0.png)

The message result in an accepted event:

![image](https://user-images.githubusercontent.com/12642168/116989210-bcc37300-acd1-11eb-8e41-cac544bc9f80.png)

The tariff ended up in the Charges table as desired:

![image](https://user-images.githubusercontent.com/12642168/116989255-d1077000-acd1-11eb-8551-90e28ff3f42a.png)

_Tariff, hourly:_
A valid charge is sent using our "Submit Addition Tariff, hourly" message with ID of "XMDJETAF02".

The message result in an accepted event:

![image](https://user-images.githubusercontent.com/12642168/116989682-5be86a80-acd2-11eb-81a2-c82f5a414ab6.png)

The tariff ended up in the Charges table as desired:

![image](https://user-images.githubusercontent.com/12642168/116989747-728ec180-acd2-11eb-9e5d-e1bd80c9d396.png)
