### ISSUE TITLE
Enabler: ServiceBus Communication - 2 - Implementing ServiceBus Channel

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#173]
As a develop
I want to make a ServiceBus implementation of GreenEnergyHub.Messaging.Transport.Channel using the AMQP-protocol
So that I can use the communication method used by the rest of the ART

For now, it is out of scope to move the changes to shared code, that is, we keep it locally in our domain.

The purpose of this story is to implement a class that is capable of transmitting a byte array onto the ServiceBus using the AMQP protocol. This class be inherit from the abstract class Channel which is part of the messaging communication strategy for outgoing messages.

A diagram of the outgoing classes can be seen below, including the Channel class which we will make a specialization of.

ACs:
AC1: An implementation of GreenEnergyHub.Messaging.Transport.Channel using AMQP to talk to the the ServiceBus has been made.
AC2: We must be able to demonstrate that a bytearray passed to the channel ends up on the ServiceBus

**Comment by bemwen** [comment]
AC1: Has been added as part of https://github.com/Energinet-DataHub/geh-charges/pull/181

AC2:
Since we are currently not using the code, I added a test that can be manually run to send to a servicebus.

As can be seen in this screenshot, the message appeared as expected

![image](https://user-images.githubusercontent.com/12642168/116878460-b2e13780-ac1f-11eb-8459-e3d6aa0f3918.png)

The test is called WriteAsync_WhenManuallyRun_EndsUpOnServiceBus.

**Comment by BjarkeMeier** [comment]
As a tester I tested the issue by executing the mentioned unit test manually and seeing the message ending up in the service bus topic as expected.

![image](https://user-images.githubusercontent.com/11583438/117294289-c33d2080-ae72-11eb-83fe-e9b4fbfe6c16.png)
