### ISSUE TITLE
Remove old Actor mega event consumption

### ISSUE THREAD

**Issue by x-platformcoder** [Energinet-DataHub/geh-charges#1730]
### Synopsis
Remove all traces of the old Actor mega event version 2 from Charges domain

### Acceptance Criteria
- [x] Given an Actor Mega Integration Event is sent to the servicebus When we have cleaned up Then we no longer consume this event
- [x]  Once the use of mega integration event has been phased out, then Titan is made aware, so that they can perform a system wide clean up. 

### Tasklist
- [x] Remove C# code
- [x] Remove Terraform code
- [x] Remove project references to old actorclient

### Tech notes
There might be some coordination on how to enable the new events and closing down the old event

**Comment by prtandrup** [comment]
### Tested in T-001:

`AC1`
First, I looked if the function MarketParticipantPersister was gone in Azure; it was:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/4c25ee3b-7658-41fa-8349-fab73fa15378)
And also, no subscription related to the ActorUpdatedIntegrationEvent in azure.

In order to trigger the `ActorUpdatedIntegrationEvent`, I changed the name of the actor related to Energinet SYO: 

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/32f2e33f-1a69-467b-88ad-41b2ad4cd18a)

The event was (as expected) published by the Market Participant domain:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/bae033d4-8e04-46d5-bbce-42701203fbd0)

And Application Insights showed no processing of the event in relation to charges:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/d490bcd6-5a82-409b-aac8-791902a6cb88)

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/78d0c25b-c2fb-41e3-bcb9-f19f9f02817c)

`AC2`

Titans was made aware:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/ee44c109-eb1d-4826-96f5-545ddc48a0ba)
