### ISSUE TITLE
Charge Links: Publish message using Protobuf

### ISSUE THREAD

**Issue by Mech0z** [Energinet-DataHub/geh-charges#366]
**Synopsis**
We have previously made a CIM/XML parser of Charge Links and now need to forward the message to the internal service bus using a protobuf contract

**Acceptance criteria**
* ChargeLinkCommands are placed on the service bus using protobuf
* ChargeLinkCommandReceiver returns a result object to the sender instead of the ChargeLinkCommand

**Testing**
Can be tested with postman using and then using https://github.com/Energinet-DataHub/hackathon-projects/tree/master/AzureProtobufHelper to read the messages
Use the following protobuf file and change the localsettings accordingly
[https://app.zenhub.com/files/345465244/30c815a8-2354-49fb-914f-a37ff6aa5f8d/download](https://app.zenhub.com/files/345465244/30c815a8-2354-49fb-914f-a37ff6aa5f8d/download)

**Comment by prtandrup** [comment]
Tested in Charges T environment.
```
Acceptance criteria fulfilled. 
Single bug detected.
```

- [x] AC1: OK, but a bug is detected: ChargeType submitted as tariff (D03) is outputtet in protofile as fee (2) 

Tariff link submitted. 
Used [AzureProtobufHelper ](https://github.com/Energinet-DataHub/hackathon-projects/tree/master/AzureProtobufHelper)tool to verify the content of the service bus published `link-command-received` message
Note: some of the enums, e.g. Document.Type needs to be verified using the proto file [here](https://github.com/Energinet-DataHub/geh-charges/blob/main/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/ChargeLink.proto). 
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/597ecfcb-e763-498d-b2df-8ef405bda9ef)

Fee link submitted (no end date). Same bug; Submitted Fee => proto outputted as subscription (1).
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/7180bb98-deab-4846-9b90-c6611df5f922)

- [x] AC2: Return result object instead of command: 

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/d9098f52-4366-459f-8810-42e0b4906a8a)
