### ISSUE TITLE
Update DateTime datatype in Database to DateTime2 

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/geh-charges#514]
**Synopsis**
The ART has decided that all time values in the Charges domain are in UTC time. But the data type we use to store our time data in does not inherently support storing that the time data is in fact UTC. 

We, therefore, wish to update all DateTime fields in our database to the DateTime2 type.

**Notes**
https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-ver15

DateTimeOffset has been considered by the SA and found DateTime2 sufficient. 

**Acceptance criteria**
1) All DateTime data types in the database must be replaced with DateTime2
2) Verify a Charge is possible to save on T

**Comment by BjarkeMeier** [comment]
@lasrinnil, regarding "_we_ have decided". I believe "we" is the ART rather than the team. Can we replace "we" with a term that removes the uncertainty?

Regarding "_But the data type we use to store our time data in does not inherently support storing that the time data is in fact UTC._" I'm unsure what this exactly means. Does it mean that the type doesn't include time zone and thus is explicit? Or are you refering to some bogous behaviour that readers of the story might not know about? Or...?

**Comment by BjarkeMeier** [comment]
**Test of story**
AC 1: This query and result from sqlsrv-charges-endk-t/sqldb-charges confirms this AC

```sql
SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'Charges' and DATA_TYPE not in ('int', 'nvarchar', 'bit', 'decimal')
```
![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/95b15377-2bc0-4bbf-8cad-d5640e7a5b05)
