### ISSUE TITLE
Charges: Save and retrieve enough information to support bundling of charge messages (Part 1/3)

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#594]
**Synopsis:**
When changes to charges are accepted we need to store enough information about the changes to be able to later bundle the information on request of the messagehub

Note: Technical story

**Out of scope:**
The following is covered in other stories:
* Generating the bundled CIM/XML
* Actual exchanges with the messagehub #595

It is also out of scope to save information on behalf of any other market participant than the grid access provider.

**Acceptance criteria:**
* The information needed to be stored has been determined and the scripts added to our deployment DB scripts
* Upon receiving accepted charges the information is stored to the database
* Given a list of ID the needed information can be retrieved
* The saving and restrieving is covered by integration test

**Comment by HenrikSommer** [comment]
Test of story:

Acceptance criteria:

- [X] The information needed to be stored has been determined and the scripts added to our deployment DB scripts:
   Screen dump of new tables in Charges MS SQL on T-environment: ![image.png](https://images.zenhubusercontent.com/60bf731f5b600c8c1257787b/14a1f8be-50f9-4502-92a0-21a0b07e6de6)

- [ ] Upon receiving accepted charges the information is stored to the database

- [ ] Given a list of ID the needed information can be retrieved

- [ ] The saving and retrieving is covered by integration test

**Comment by bemwen** [comment]
**Test result on last AC - PASSED**

NOTE: Test performened on U-002 environment because of right access issue on T-environment at the moment.

A tax charge is sent (with only 1 active grid access provider):

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/774096d2-f72f-4e36-9e6b-8b5121bc768b)

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/3e7152a5-6ec2-4158-9124-a567bf734468)

The charge master data is saved into AvailableChargeData

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/cc296ada-2df4-4661-8f91-ffcfb4fdd492)

The prices are saved into AvailableChargeDataPoints

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/2f31cfea-8238-483d-bf7e-4cab781794d1)

Test PASSED.
