### ISSUE TITLE
Schema validate CIM XML for time series

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#609]
**Synopsis:**

We need to coordinate some issues for use of schema validation, and B2B validations in general, before we can implement the XML Schema validation.

**Acceptance criteria**
* It has been determined ​what HTTP status code should be returned on failed schema validations
* It has been determined where the code XML schema validation should live
* The process of determining what to do with results from B2B validation has been started and the status written on this story

**Comment by bemwen** [comment]
**API Management:**
Talked with Mighty Ducks and Architect. The API Management will just forward the call to the correct domain endpoint for each message sent from outside.

It will be up to each individual domain to send the correct HTTP status code and response back to the sender. A process will be started to determine how and what to reply so that the market participants will get the same type of response from each domain.

**XML schema validation:**
It has been agreed that schema validation should probably be a nuget package so all domains can share it, but the location has not yet been determined.

Architect input to requirements: We should aim for providing a new implementation of XmlReader so that each domain only have to make a single passthrough of the CIM XML fall when building their internal objects. While the domain builds, the Reader should check the schema and provide a way for the domain to check that at the end of the process.

**Comment by bemwen** [comment]
Answers to ACs:
It has been determined ​what HTTP status code should be returned on failed schema validations - We should respond with HTTP 400 Bad request on schema validations

**Comment by HenrikSommer** [comment]
Test of story:

- HTTP status code returned on failed schema validations is determined
- It is verified that the determined place for the code XML schema validation exists
- According to the _Answers to ACs_ the process has started

In conclusion, this story is tested to be correct
