### ISSUE TITLE
Enabler: Prepare for quering historical data (CQRS refactoring)

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-charges#628]
**Synopsis**

Make technical clean up of debt related to CQRS decision and make preparations for upcoming feature requirements regarding e.g. historical data in GUI and data requests.

**Tech Notes**

See POC in https://github.com/Energinet-DataHub/geh-charges/pull/768.

**Acceptance-Criteria**

There are no specific ACs, but the dev team will work with the PO in order to determine when and how much to work on in the following prioritized list of tasks. Though it is prioritized many of the tasks can be done in parallel or different order.

- ~~[ ]Add history model in read database (that probably means in a new SQL table with another schema name - perhaps "read" or "query" or....?)~~
- [x] Remove history model from command stack (charges and charge links) - this implies replacing it with a storage model that is aligned with the domain model. It also implies fixing the erroneous charge link domain model
- [x] Use EF Core fluent configuration for all aggregate roots
- ~~[ ] Populate charge and charge link history read models on accepted events~~
- ~~[ ] Scaffold read model DbContext using a script that can be easily invoked by all developers regardless of chosen IDE~~
- ~~[ ] As a POC expose an HTTP REST endpoint that can provide those of the GUI required data that we have at hand~~

**Comment by BjarkeMeier** [comment]
Moving the old story description to this comment as we are now beyond the issues addressed there. Instead PO have requested a story that addresses initial technical stuff that can be done in order to prepare for the upcoming UI and data request needs.

**Synopsis**

As developers
We need a decision about our architecture for the relation between commands and queries
And we need existing code to be refactored to match the decision
So that we can keep the system maintainable and avoid building up technical debt

The development team has agreed that this issue is so big that it needs a story of it's own.

**Tech-Notes**

- The development team has (more or less?) decided to go with CQRS. So the story is probably more about getting an agreement on the actual code design and do the actual implementation and refactorings.
- Operations and PeriodDetails of charges and charge links belongs to the read model
- Domain model and storage model (SQL) should be very closely aligned
- Consider to write into the current data model upon Accepted events to make it act more like a query model
- Consider FluentConfiguration and how we should use it (architect wish to use)

**Acceptance-Criteria**

1. An architectural decision about commands and queries has been agreed by the development team
2. All domain models are aligned regarding using EF Core fluent configuration or not
3. All domain models are aligned regarding whether they expose history or not (like chargelink.operations and chargelink.perioddetails)
4. All code has been refactored to adhere to the architectural decision
5. The code design has been accepted by the development team

**Comment by Mech0z** [comment]
Scaffolding in CLI 
Using
https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding?tabs=dotnet-core-cli
Command help https://www.entityframeworktutorial.net/efcore/cli-commands-for-ef-core-migration.aspx

Navigate to C:\Git\geh-charges\source\GreenEnergyHub.Charges\source\GreenEnergyHub.Charges.QueryApi

dotnet ef dbcontext scaffold "<<YOUR CONNECTIONSTRING>>" Microsoft.EntityFrameworkCore.SqlServer --output-dir ScaffoldedModels --context-dir ScaffoldedModels --context ChargesdatabaseContext --force

**Comment by BjarkeMeier** [comment]
As the team is getting more aligned on being value-focused, I've removed (strike through) the AC's that are better driven by business value stories.

**Comment by HenrikSommer** [comment]
Testing, OK!

History model has been removed from the Charge command stack:
![image.png](https://images.zenhubusercontent.com/60bf731f5b600c8c1257787b/4a7695e0-4ed9-40dc-b10b-172e6a7389a5)

and connected to the SQL-model using fluent configuration:
![image.png](https://images.zenhubusercontent.com/60bf731f5b600c8c1257787b/e9e54dad-c40b-4204-8f17-a94e09373114)

again?
![image.png](https://images.zenhubusercontent.com/60bf731f5b600c8c1257787b/39481c43-f02f-432c-b99f-44a7d338d25e)

SQL tables for Charges have been shrunk to contain only Charges and ChargePoints:
![image.png](https://images.zenhubusercontent.com/60bf731f5b600c8c1257787b/a7067082-8368-4a1a-a905-2cd5de4df633)

The same for ChargeLinks:
![image.png](https://images.zenhubusercontent.com/60bf731f5b600c8c1257787b/3f40fa6c-2214-48cd-a9a3-2f27e93514e1)

Resulting in a nice lightweight database:
![image.png](https://images.zenhubusercontent.com/60bf731f5b600c8c1257787b/9d74d6da-3316-4210-9e11-68b8f47671ce)
