### ISSUE TITLE
Bug: When publishing a ChargeLinkCreated event the Factor value is always 1 even though the ChargeLinkCommand had another value

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#666]
Issue observed while doing this test in the T-environment.
Problem is rooted here `ChargeLinkCommandFactory.cs` line [114](https://github.com/Energinet-DataHub/geh-charges/blob/233b9044eab6052da3d9b1805b476db8088e5c5c/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/ChargeLinkCommands/ChargeLinkCommandFactory.cs#L114).
It supports both the default charge link way and the regular charge link request way, defaulting factor to 1 doesn't do for the latter.

- Create fee link (fee: 334_fee)
Correlation ID: 08445de1-f969-4d05-b318-39d5e649e7c6
CIM XML submitted with start date + end date + factor 2
Stored correctly:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/042ee132-f724-4545-a40c-e0326d948bf8)

Issue detected: Factor is published as 1 (see below), when it was provided as 2.
````
{
  "ChargeLinkId": "832d8c0f-12d1-40d6-b489-67ee50f8f26e",
  "MeteringPointId": "571313180000000005",
  "ChargeId": "334_fee",
  "ChargeType": 2,
  "ChargeOwner": "8100000000030",
  "ChargeLinkPeriod": {
    "StartDateTime": {
      "Seconds": 1635721200,
      "Nanos": 0
    },
    "EndDateTime": {
      "Seconds": 1640991600,
      "Nanos": 0
    },
    "Factor": 1
  }
}
````

**Comment by bemwen** [comment]
**Test result - PASSED**

NOTE: U-002 environment was used instead of T because of the current situation of missing rights in the T environment.

A charge link is sent:

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/1eabdd36-e6af-49cc-88ef-70623a9335b2)

In the database the factor 8 has survived:

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/208ee03b-4f70-4e87-9447-f27a02d53110)

And the integration event also has the correct factor:

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/171b8cd2-4f63-4905-b286-90b37eb10bff)

Test PASSED.
