### ISSUE TITLE
Add domain test: Submit new Charge and verify the integration events (ChargeCreated + ChargePricesUpdated) are published

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#716]
**Synopsis:**

With this story we cover the following flow and entry/exit points with a single domain test:
- **Flow**: Create new Charge (this can be either a tariff, fee or subscription)
- **Entry**: ChargeIngestion
- **Exit points:** Integration events (ChargeCreated and ChargePrices)

![NewCharge_IntegrationEvents.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/eb576600-724b-4d0f-8ec8-b86d801ca9a9)

**Acceptance criteria:** 

Given a new charge (new combination of Charge Type, Charge Id and Owner), including one or more prices
When it is submitted to the Charges Domain (as a RSM-033 CIM XML)
Then a `ChargeCreated` integration event is published
And it is asserted that it is the expected Charge (Type, ChargeId and Owner)
And a `ChargePricesUpdated` integration event is published
And it is asserted that it concerns the expected charge and that one price is correct.

**Comment by Mech0z** [comment]
@prtandrup, we segregated the following from the story in order to keep it focused. Perhaps this could be maintained somewhere shared if you find it important?

As team Volt
We want to implement domain tests covering our already existing entry/exit points
So that we have insights into the quality of the domain and enable us to react upon quality deterioration before deploying software to any environments.

**Tech notes:**
Domain tests are considered black box tests and thus we only focus on domain input/output.
The test must be categorized as a DomainTest, just like we use [UnitTest] for unit tests (xUnit categories), and it is placed in a (perhaps already existing) domain test project, perhaps part of this work (Please have a look at what was introduced by #691)

- [ ] AC1 The following domain test has been implemented and can be executed from localhost and as part of our CI:

**Comment by HenrikSommer** [comment]
Testing is done primarily on developer machine, with the addition of verification of tests run in the CI pipeline:

1. A valid CIM XML with unique Type, Owner and Role is in use by the two integrationtests:
![1_TaxTariffWithPrice_CimXml_forTest.png](https://images.zenhubusercontent.com/60bf731f5b600c8c1257787b/ab80a813-806c-4657-935c-af4957aa78e1)

2. Each test creates a valid request using the valid CIM XML:
![2_CreateHttpRequst_with_CimXml.png](https://images.zenhubusercontent.com/60bf731f5b600c8c1257787b/80582471-98f8-42e0-8b32-1e474072e6a1)

3. Result of the _When_ChargeIncludingPriceIsReceived_Then_ChargePricesUpdatedIntegrationEventIsPublished_ test:
![3_ChargePriceUpdatedEvent_Received.png](https://images.zenhubusercontent.com/60bf731f5b600c8c1257787b/8ed0672f-d86c-4218-9834-7151c5f1e019)

4. Result of the _When_ChargeIncludingPriceIsReceived_Then_ChargePricesUpdatedIntegrationEventIsPublished_ test run in CI pipeline:
 ![image.png](https://images.zenhubusercontent.com/60bf731f5b600c8c1257787b/ff94de58-22e5-4ea9-a964-dbc4a7bf1312)

5. Result of the _When_ChargeIsReceived_Then_ChargeCreatedIntegrationEventIsPublished_ test:
![4_ChargeCreatedEvent_Received.png](https://images.zenhubusercontent.com/60bf731f5b600c8c1257787b/c1ae2b25-ccdc-491a-b7b5-f21a24d246e6)

6. Result of the When_ChargeIsReceived_Then_ChargeCreatedIntegrationEventIsPublished_ test run in CI pipeline
![image.png](https://images.zenhubusercontent.com/60bf731f5b600c8c1257787b/131044f8-5e60-4765-ae43-387347916400)
