### ISSUE TITLE
Operation ID for charge links is lost

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-charges#886]
This property should be provided by the sender:
![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/4baa07c5-209d-4409-a5fa-0ffed3187e13)

But apparently it's not:
![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/dfc72f74-9154-4394-9198-08583adcbffd)

**Comment by bemwen** [comment]
It turns out this bug wasnt an issue. Rather, it confused because of the naming of the class.

ChargeLinksCommandFactory is only used when creating Default Charge Links. A command is not used as part of the normal BRS-037 flow as the command is the direct output of a protobuf contract.

So, long story short, the code works.

I am opted to rename the factory as a "fix" to this bug as it was clearly causing confusion.
