### ISSUE TITLE
Tech: Segregate MessageHub into it's own stack

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-charges#946]
**Synopsis**

Improve maintainability of the system by segregating the concerns of MessageHub communication from core business.

**Acceptance-Criteria**

AC1
Application, Domain and Infrastructure projects no longer holds any MessageHub related code.

AC2
MessageHub code has a design and and architecture that is suitable for this kind of software.

**Tech Notes**

This story was selected by the dev team for the upcoming sprint 7.1.

Please note that the solution might imply introducing a new event to support the reply in BRS-004.
The dev team decided to host in the existing function host.
Michael suggested that the number of function endpoints could be even more reduced.

**Comment by bemwen** [comment]
*AC1:*
Only found IHubSenderConfiguration i Domain and its implementation in infrastructure which appear to be message hub specific.

Otherwise I found no trace of the message hub in Application, Domain or Infrastructure

*AC2:*
MessageHub design and architecture has mostly been left as designed, with the exception of splitting BRS-004 flow a bit. Rather, the code has been moved around to be easier to read and understand.

It seems appropriate for the software use.

**Comment by BjarkeMeier** [comment]
The hub sender configuration as per Michael's test comment is being fixed in PR #986.

**Comment by BjarkeMeier** [comment]
Well, it _is_ actually used in order to create e.g. recipient in `ChargeLinksCommand`. See `source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeLinksCommands/ChargeLinksCommandFactory.cs`. So I disagree with the test comment that it could/should be moved to the message hub stack.
I consider the story done.

**Comment by HenrikSommer** [comment]
AC1:
I have reviewed the IHubSenderConfiguration and its implementation with the developer and I see no Message Hub specific code, hence I agree that the acceptance criterion is fulfilled.
